### ISSUE TITLE
[BUG] Admin page does not work in Chrome 

### ISSUE THREAD

**Issue by dev-mcm** [ProgressiveCoders/Spoke#1036]
Recently deployed through the one click deployment to heroku. After logging in through Chrome I can not create new campaigns and do not see any of the admin links in the left hand rail, only "switch to texter"
![image](https://user-images.githubusercontent.com/6991397/50777185-eb97be80-1268-11e9-8bb2-1ea6a99aa9a9.png)

When accessing the same page via Safari (or Firefox) the admin interface appears as normal
![image](https://user-images.githubusercontent.com/6991397/50777657-29e1ad80-126a-11e9-86c6-5f23af54c9f6.png)

cc @harpojaeger and @lperson

**Comment by shakalee14** [comment]
We have a pr https://github.com/MoveOnOrg/Spoke/pull/1011 that should resolve this issue going forward. If you check your DB and delete the entries for the 'ADMIN' and 'TEXTER' for your user_id in 'user_organization' table, this should fix it. 

Thanks for filing an issue!

**Comment by dev-mcm** [comment]
@shakalee14 I've made this update, but it seems to have introduced a new issue where logging in now takes me to the "You are not a member of any organization" page, which is happening in both Chrome and Safari, is there a workaround for that bug?

**Comment by shakalee14** [comment]
This is a known bug : https://github.com/MoveOnOrg/Spoke/issues/1032 that will be fixed with this pull request (and fixed with this pr: https://github.com/MoveOnOrg/Spoke/pull/1033). These will be merged this week and are being tested currently.

In the meantime, you should be able to navigate to with no issue: https://[spoke heroku url]/admin/1/campaigns. Since this is a new instance, I'm assuming 1 because it's the first organization you've created.

**Comment by dev-mcm** [comment]
that URL does work, thank you!

**Comment by shakalee14** [comment]
This should be fixed in main now that #1011 is merged
