### ISSUE TITLE
Strengthen local auth for production use

### ISSUE THREAD

**Issue by azuzunaga** [ProgressiveCoders/Spoke#1093]
Hi @schuyler1d, I've been giving some thoughts on how to strengthen local auth for production use, and below are a series of features I think would get us there (heavily inspired by [this](https://stackoverflow.com/questions/48345922/reference-password-validation) and [this](https://blog.codinghorror.com/password-rules-are-bullshit/)). Let me know what you think.

- [ ] dev / prod toggle.
- [ ] Minimum length requirement. I suggest 12 characters.
- [ ] Check against most common passwords.
- [ ] Check for repetitive characters.
- [ ] Check for dictionary words.
- [ ] Check that email / url is not the same as the password.
- [ ] Check and display password strength to user.
- [ ] Limit login attempts before locking the account, requiring an admin to reset the user's password. I suggest 5 attempts as the limit.
- [ ] Implement two-factor authentication with a secret key / QR code that can be scanned.
- [ ] **Stretch**: suggest passwords by generating random word combinations (similar to what 1pass does when creating an account).

**Comment by schuyler1d** [comment]
What do you mean by a dev/prod toggle?

I think we should keep things simple.  I would recommend that we focus (and at least start with):
* Rate limiting login attempts (I don't think we need to lock anything) -- generally you can ratelimit by IP -- just log failed login attempts from the last X (maybe 100?) IP addresses or something -- let's try to find a node passport/express library that does this rather than write our own.
* If there's a two-factor auth passport module, let's add that (and make a setting that can enable it and/or require it for either all ADMIN/OWNER accounts OR require it for all accounts).

I'm a little suspicious of password strength or annoying setups -- a lot of texters are just coming to text and their access doesn't need to be highly secured.  If we are worrying about that kind of thing, I'd rather add support for e.g. Google auth -- which has a more robust security model (including spying on everything you do everywhere :-)

**Comment by azuzunaga** [comment]
The dev/prod toggle was in the context of enforcing password strength only on production, minimizing friction while developing. But I see your point about annoying password requirements (I actually just had a password rejected for being too long 🤦‍♂️). However, should we enforce _some_ sort of password requirements for admins/owners?

I'll start looking for a rate limiting module. I found [Speakeasy](https://github.com/speakeasyjs/speakeasy) for two-factor authentication, but I'll do some more research just in case.

I guess if highly secured access is a requirement we should recommend auth0 is used?

**Comment by schuyler1d** [comment]
Yeah, auth0 has google auth, e.g. and maybe 2fa?  so maybe that's the recommended solution for anything sophisticated.  At least for any policy we have it should definitely not stop anyone from having a *longer* password.

I suppose we could just have a required ?8 or ?10 characters for admins/owners?  Let's not go nuts unless we hide it behind a feature.  Honestly, a key goal for local auth is something that is simple -- so let's not add complexity which removes the key feature! :-)

**Comment by azuzunaga** [comment]
Yep, auth0 also has 2fa!

I agree with you, and I think based on this thread we can leave local auth as-is, and in case an org has stricter security requirements they can switch to auth0.

If you agree, let me know and I'll close this issue :)

**Comment by schuyler1d** [comment]
:+1:
