### ISSUE TITLE
Add cool features from politics-rewired fork

### ISSUE THREAD

**Issue by joemcl** [ProgressiveCoders/Spoke#1157]
See https://github.com/politics-rewired/Spoke . This is more of a Project than a single Issue, but I want to get it started. 
There are a number of cool features in this fork - for example, an Escalate function to bump convos 'up' for others to field. That seems part of a solution for doing things like referring Spanish-language replies to Spanish-literate texters, asking for help on responses to thorny questions, updates re a policy question not addressed in Canned responses, etc.

**Comment by schuyler1d** [comment]
I'm marking this as meta -- @joemcl please create individual issues -- at least with the things you would mark as wfp-priority.  There's a LOT in politics-rewired, and there's a bunch of stuff we might not accept (at least, as-is)

In each issue, please DO include a link to this issue, so we can track them together.

**Comment by joemcl** [comment]
Cool @schuyler1d makes sense.

**Comment by joemcl** [comment]
Adding a link to some docs about this fork which are at https://docs.spokerewired.com/ .

**Comment by ibrand** [comment]
Gonna close this issue because at this point, we're seeing different features make their way in through feature request issues and RFC project proposals. If there are any particular features that you don't see in the [project proposals](https://github.com/MoveOnOrg/Spoke/issues?q=is%3Aopen+is%3Aissue+label%3A%22C-Project+Proposal%22) or other [feature requests](https://github.com/MoveOnOrg/Spoke/issues?q=is%3Aopen+is%3Aissue+label%3AC-enhancement+) that you'd like added, feel free to add an issue!
