### ISSUE TITLE
Bug: Spoke Not Scrubbing Opt Outs From Larger Organizations

### ISSUE THREAD

**Issue by shakalee14** [ProgressiveCoders/Spoke#1198]
**Describe the bug**
When I upload a list with opt outs into an organization with a large amount of contacts, Spoke will upload the list and create new campaign contacts for the opted out contacts. Spoke will not allow texters to send texts to the opted contacts, but texters will see these contacts in their todo list. This causes confusion since these contacts are not contactable.

**To Reproduce**
1. Go to an instance with an organization with a lot of contacts (cannot reproduce on a smaller organization, within the same instance)
2. Click on create a campaign, and upload a csv with opted out contacts. 
3. Click 'upload contacts'
4. In our instance - we see an unfinished progress bar, and all of the contacts count appear in the texter assignment admin panel. When we click 'cancel job', it turns the contact section green, but doesn't scrub them out.
5. Assign texts to texter - login to texter account - and attempt to send texts (they shouldnt send, and these contacts should be still marked as 'needsMessage' in the `campaign_contact` table.

**Expected behavior**
Opted out contacts should be scrubbed out on the initial upload and the number of deleted should appear in a message.

**Screenshots**
The initial scrub  should report here:
<img width="829" alt="Screen Shot 2019-08-14 at 2 56 30 PM" src="https://user-images.githubusercontent.com/16676323/63048090-c70d6000-bea3-11e9-8e92-821ebfb01e13.png">

**Desktop (please complete the following information):**
 - OS: n/a
 - Browser n/a
 - Version n/a

**Smartphone (please complete the following information):**
 - Device: n/a
 - OS: n/a
 - Browser n/a
 - Version n/a

**Additional context**
I cant reproduce this issue locally, on staging or in the same instance but in the test organization. This only occurs in our production organization.

**Comment by schuyler1d** [comment]
Some guidance about code points:
Optouts should be excluded in this code: https://github.com/MoveOnOrg/Spoke/blob/main/src/workers/jobs.js#L262-L269
You'll notice that this calls [getOptoutSubquery which is defined further up in the file](https://github.com/MoveOnOrg/Spoke/blob/main/src/workers/jobs.js#L52-L84) -- further that it and several optout functions are duplicated (a dittographic error) -- which we should probably remove while fixing this bug.

The bug is likely in this area and if it's identified it should also be fixed here for datawarehouse loading:
https://github.com/MoveOnOrg/Spoke/blob/main/src/workers/jobs.js#L430-L440

One other possibility if this is an unreliable bug is that somehow the upload process is cutoff before the deletion moment -- in that case, perhaps we can confirm that by looking at Lambda cloudwatch logs when it occurs.

I believe there are currently no tests for processing an upload -- we should rectify that.  If you do, you should create another file -- maybe model the header off of __test__/server/api/campaign.test.js which creates a campaign, an admin user, etc.  You'll also want to create some optouts!

If you make a test purely for `uploadContacts` then you might want to make a 'wrapper' function so you don't have to compress the data, etc for the 'job' argument that's passed.  In terms of what contacts to upload, you can generate junk and/or use the __test__/test_data/female_scientists.csv file
