### ISSUE TITLE
Feature Request: Marking your own texts for reassignment

### ISSUE THREAD

**Issue by allisonChilton** [ProgressiveCoders/Spoke#1377]
**Is your feature request related to a problem? Please describe.**
Reassigning tasks is time consuming for campaign staff, and requires constant monitoring of Slack.

**Describe the solution you'd like**
The user should be able to mark their own texts for reassignment, which submits the texts to a priority assignment pool. When a different volunteer requests a new batch of texts, they should be able to pull automatically from the reassignment pool without needing campaign staff to reassign. This will allow for a more optimized workflow.

**Comment by arena** [comment]
I was going to add this one but @allisonChilton beat me to it. :)
As I think about the Campaign Card that appears on the Texter Dashboard I think there should be a more actions section (maybe a menu at the top right of each card .. pretty standard) and I could see that menu having something like "reassign"

The thing that is confusing to me as a texter (or that wasn't intuitive) is that the whole batch needs to get reassigned including the sent messages. Otherwise new replies will come in on that list and the texter (me) could easily miss them if the entire assignment (segment of the contact list) wasn't reassigned.

**Comment by Frydafly** [comment]
It would be helpful if this feature included the ability to comment on the reason for skipping, one of the more common reasons being that the user does not speak the language of the texter. This could make it easier for another user that speaks a certain language to pick up those texts.

**Comment by ibrand** [comment]
This would be covered by this RFC: #1533 which proposes that you'd be able to request texts and "release" texts (have your own texts reassigned.) This is similar to how the Warren campaign did reassignment. @Frydafly @arena and @allisonChilton would love for you all to weigh in on that!

**Comment by allisonChilton** [comment]
Fixed by #1702 I think
