### ISSUE TITLE
Feature Request: Allow deletion of a user from the People page

### ISSUE THREAD

**Issue by ibrand** [ProgressiveCoders/Spoke#1487]
**Problem**
Admins currently can't delete a user. Regularly, a user will accidentally end up with 2 accounts and then the admin needs to go into the DB to delete the account that shouldn't exist.

**Solution**
Let's add a red delete button to the edit modal that appears once you hit edit on the people page. I'm a little unsure on the best positioning here.

**The edit button that opens the modal**
<img width="1440" alt="Screen Shot 2020-04-16 at 6 46 06 PM" src="https://user-images.githubusercontent.com/3953117/79514080-578fd780-8013-11ea-9f57-641690caa865.png">

**Potential place for a delete button in the modal**
<img width="776" alt="Screen Shot 2020-04-16 at 6 47 15 PM" src="https://user-images.githubusercontent.com/3953117/79514107-670f2080-8013-11ea-9eb3-1baea4161dea.png">

**Comment by JeremyParker** [comment]
@ibrand should this just be a hard delete? Or a soft delete where there's a field like `deleted=true` so users can be undeleted if necessary?

**Comment by JeremyParker** [comment]
Also, a user can't delete themselves, right?
http://localhost:3000/app/1/account/1

**Comment by ibrand** [comment]
> @ibrand should this just be a hard delete? Or a soft delete where there's a field like `deleted=true` so users can be undeleted if necessary?

Caught up with @JeremyParker but wanted to document our conversation. We decided to stick with a soft delete so that if a texter is assigned to a campaign and then is deleted there's no weird data issues that will emerge. Jeremy brought up user deletion and GDPR and we decided to prioritize lack of data corruption and issues and I want to make a note that we should eventually write a query into the [SQL Queries doc](https://github.com/MoveOnOrg/Spoke/blob/main/docs/TEXTER_ACTIVITY_QUERIES.md) for hard deleting users for GDPR and full account deletion but to mark to use it with care.

> Also, a user can't delete themselves, right?
> http://localhost:3000/app/1/account/1

We also talked about this one. We decided that this is not mandatory for this issue, but would be a great nice to have!

**Comment by schuyler1d** [comment]
I'd like to suggest that we change how this works to be suspendable from the People page by adding another role into the ROLE_HIERARCHY.
Thus SUSPENDED would be a choice where TEXTER, ADMIN, OWNER are now.
Then, by default users with role SUSPENDED would be excluded on the people page and the texter list.

Some code points:
Add a role in front of TEXTER:
https://github.com/MoveOnOrg/Spoke/blob/main/src/lib/permissions.js#L1
Add it to the enum here:
https://github.com/MoveOnOrg/Spoke/blob/main/src/server/models/user-organization.js#L16
And then here:
https://github.com/MoveOnOrg/Spoke/blob/stage-main/src/server/api/user.js#L61-L68
You'll want to do something like add a `whereNot('role', 'SUSPENDED')`, maybe *unless* role === "SUSPENDED" (so you can still explicitly search for them).

There might be a couple of other places to tweak, but I think that should do most of it.

I would suggest branching off of this PR, since the People page is changed quite a bit in there:
https://github.com/MoveOnOrg/Spoke/pull/1538

**Comment by ibrand** [comment]
This will take the place of #1350 -- using the SUSPEND status will work for both the concept of "deleting" a texter who made an account by mistake or just wants theirs deleted and the concept of suspending a texter that an admin wants removed

**Comment by ibrand** [comment]
This means this will also close #1005, #1323 and #1055
