### ISSUE TITLE
RFC: Allow Campaign to have their own twilio messaging service

### ISSUE THREAD

**Issue by hiemanshu** [ProgressiveCoders/Spoke#1495]
##  Proposal
This proposal outline idea of adding support for each campaign to have its own Twillio messaging service. This work is based off the Warren fork [here](https://github.com/Elizabeth-Warren/Spoke/), which includes some back porting, and some original work to bring this feature over. 

## Motivation
There are multiple motivations behind the idea, the main one being allowing Campaigns to send more than 80k messages per day (Twilio determined limit) and allow campaigns to have regional phone numbers associated with them, for example, having a campaign local to a state associated with a messaging service that uses phone number from that local region.

## Detailed Design
The proposal has three big components associated with it:
1. Updating campaign configuration workflows:
- Add a new variable (default false) to create a messaging service when creating campaign
- Create a new messaging service and assign to campaign if checkbox is true
- List details about messaging service in Campaign details page about phone numbers, total numbers, link to manage service in Twilio

2. Updating the Twilio library to handle messaging based on a campaign's configured messaging service.
- Get configured messaging service from campaign
- Configure Twilio to use the configured messaging service

3. Adding a way to buy multiple phone numbers for a messaging service:
- Add support to Twilio library to bulk buy phone numbers based on area code
- Add command line interface to buy numbers in bulk

#### Sponsor Organization (will test alphas/betas)
The plan is backed by Resistance Labs.

#### Developer allocated
I(@hiemanshu) will be working on this. 

#### Planned timeline
The estimate for the work involved is 2.5 days of dev time, and 0.5 days of testing. 

#### Files/File-sections touched
Sections being changed:
- Campaign -- Model/Schema, UI changes, Tests
- Twilio -- Library changes, Tests

#### Existing github issues that this RFC will address
- Using multiple messaging services will allow phone numbers in area code per campaign (#1259)
- Will expand on allow Twilio per organization (#580)

**Comment by matteosb** [comment]
Hi @hiemanshu, thanks for putting up this RFC!  

While creating a Messaging Service and asking the admin to allocate numbers to it manually is a good first step, I think the process for purchasing numbers and allocating them to campaigns needs to be fleshed out. Otherwise campaigns will start in a non-functioning state and I think that would be a difficult user experience. I'd really like to see this feature eventually provide organizations with a way of managing phone numbers without needing to interact with Twilio or the command line at all.

I think there are really two options here: buy numbers on-the-fly when the campaign starts like some vendors do, or implement a separate phone number inventory system like the Warren fork did. My preference is for the latter, as it makes it possible to re-use numbers efficiently and gives admins visibility into what area codes they are going to get. It also allows organizations to buy numbers ahead of time in area codes with limited availability, which is a common problem around elections. On the other hand, buying numbers on the fly might be a little bit simpler because it doesn't require a separate phone number buying step outside of campaign creation, nor does it require additional database tables. @schuyler1d @ibrand and @jeffm2001, do you have a preference?
 * Buying numbers on the fly changes the design significantly from the Warren version: it would require admins to provide a list of preferred area codes in campaign set up and an error state if the application fails to find sufficient numbers when starting a campaign.
* For inventory management see the `twilio_phone_number` table in the Warren fork and associated functions in [src/server/db/twilio_phone_number.js](https://github.com/Elizabeth-Warren/Spoke/blob/master/src/server/db/twilio-phone-number.js). Unlike the Warren fork, I would suggest that we scope the inventory to organizations by adding an `organization_id` column. The inventory could be further extended to manage the instance-wide and/or organization Messaging Service for organizations that don't want to use campaign-specific messaging services.


Regardless of which of the two approaches is taken, we would additionally need to:
1. make the `startCampaign` mutation kick off a background job so phone numbers can be transferred to the messaging service (or purchased) when the campaign starts ([Warren code](https://github.com/Elizabeth-Warren/Spoke/blob/master/src/server/api/mutations/campaign.js#L14-L45)). Starting a campaign should also have some sort of loading indicator.
2. have some process for releasing numbers. In the Warren fork this was done by completely reworking campaign statuses: we added two states (CLOSED and CLOSED_FOR_INITIAL_SENDS, which allowed texters to reply) and made archiving irreversible, allowing us to release numbers after archiving. I think that might be too much change for the MoveOn fork, so I would propose just adding a button to explicitly release numbers on archived campaigns, after which the campaign could no longer be unarchived.

If we go down the inventory management route like the Warren fork, we would have to add two more things:
1. a background job to buy phone numbers so that we can eventually provide a UI in the Admin interface ([Warren code](https://github.com/Elizabeth-Warren/Spoke/blob/master/src/server/workers/buy-numbers.js)). A command line tool that also writes to the `twilio_phone_number` table could solve this in the short term, but I personally think kicking off the job with a mutation through graphiql is easier, especially when the database isn't accessible from peoples' machines.
2. a cron job to release "reserved" phone numbers after a period of time so that unstarted campaigns don't hold numbers indefinitely.

**Comment by schuyler1d** [comment]
Organization inventory vs campaign inventory:
* I think I would definitely like an organization inventory, at least as a default.
  - another value of keeping organization inventory, is that we can track a numbers' use and deliverability across campaigns

* A slow campaign start and irreversible archive for number release is only necessary with per-campaign number buying, right?
  This suggests to me, it should be an optional setting

* When a campaign starts, perhaps it starts with organization inventory, and then supplements it with campaign inventory? (if the environment variable is enabled for MESSAGESERVICE_PER_CAMPAIGN).

* With organization inventory, if some of them are 'allocated' to a campaign, we could also avoid a 'big buy'/'big drop' job, just by an incremental (and thus possibly re-runnable in shorter-lived segments), allocate/deallocate X campaign numbers.  i.e. SELECT...,

* I'd like to make sure that messageservice details are in-cache (when available).
  Something about to be merged in our 5.4 release is this method:
  https://github.com/MoveOnOrg/Spoke/blob/stage-scaling-message-caching/src/server/models/cacheable_queries/organization.js#L14
  used in server/api/lib/twilio.js:
  https://github.com/MoveOnOrg/Spoke/blob/stage-scaling-message-caching/src/server/api/lib/twilio.js#L145
  With `contact` passed, you should be able to get `contact.campaign_id`

  I'd like this work to be aware of (possibly fork off of) and collaborate with is @jeffm2001's PR:
  https://github.com/MoveOnOrg/Spoke/pull/1478
  (which I think actually simplifies/better separates out the auth from the messageserviceid)

====
A meta note:
I'd like to see this RFC (or a new one during collaboration) include more detail on *files* that are touched.

**Comment by jeffm2001** [comment]
Super excited about this, and happy to help in any way I can.

- I definitely think an inventory of number is the way to go. If for no other reason than if you're buying numbers on the fly for each campaign, those costs will add up.

- Another thought on how it could be structured: instead of (or in addition to?) an organizational inventory of phone numbers, you could have named "number pools" (message services), which you could buy/assign numbers to in the admin interface. In campaign creation, you would select from the available number pools.

  - For example, you create a "Wisconsin" number pool, with all the relevant area codes, and use it for your campaigns in the state.

  - Potentially, this solves the releasing numbers problem, since the number continues to live in the pool for use on further campaigns.

  - It is probably less efficient at fully optimizing number allocation since if you are running multiple campaigns in the same state, you either need to make the pool big enough to handle both or create separate pools. (Although that's no worse than what exists now). There are probably other drawbacks to this model I haven't thought of.

- In my PR (#1478) I labeled the `TWILIO_MESSAGE_SERVICE_SID` setting as "Default Message Service SID" with the idea that there could be a fallback message service if one is not configured for a campaign. That may or may not make sense, depending on where we end up.

**Comment by matteosb** [comment]
Ok, it sounds like we are all aligned around having an inventory. I'm going to start a separate RFC and/or a Google doc to dive into the details. 

Let's keep this RFC scoped to the mechanics of using a separate messaging service per campaign - regardless of how that service is populated. @hiemanshu's proposal sounds good to me :+1: . I agree with @schuyler1d that caching the campaign -> messaging_service_sid mapping is a requirement and that it should be based off of #1478.
