### ISSUE TITLE
Feature Request: Embed Chat/Support Widget

### ISSUE THREAD

**Issue by Frydafly** [ProgressiveCoders/Spoke#1541]
**Problem**
As we expand to multi-tenant use of Spoke at NY Civic Engagement Table, we would like to streamline support requests from organizations, canvassers, volunteers. 

We would like our admins and texters to first review our knowledge base for solutions, and then reach out to us with a support ticket if the knowledge base does not address the issue.

I tried to use the HTML header feature for each campaign to embed our support page, but it looked messy, and would confuse texters that are assigned to multiple campaigns.

**Solution**
Allow an organization to inject code for a chat widget, so that something like this could pop up in the main admin page and the campaign page for texters:

<img width="331" alt="Screen Shot 2020-05-06 at 11 49 20 AM" src="https://user-images.githubusercontent.com/22733009/81234932-cdaaad00-8fc7-11ea-853c-752003ae7407.png">

Here's the code for our orgs' widget:

```
 <script>
	window.fwSettings={
	'widget_id': ID_NUMBER_GOES_HERE
	};
	!function(){if("function"!=typeof window.FreshworksWidget){var n=function(){n.q.push(arguments)};n.q=[],window.FreshworksWidget=n}}() 
</script>
<script type='text/javascript' src='https://widget.freshworks.com/widgets/ID_NUMBER_GOES_HERE.js' async defer></script>
```

**Context**
This feature would help NYCET manage issues and support requests coming from our 60 orgs that will eventually all be using Spoke.

**Comment by ibrand** [comment]
As part of work in #1533 Texter Sideboxes now exist. This support widget would make a lot of sense as a sidebox extension because it would be:
- optional but easy for NYCET to add
- Pretty straight forward from a UI perspective and wouldn't touch or change any existing UI patterns in the texting UI
- Isolated code-wise

**Code points / patterns**
- Adding 1 folder and then 1 react file in that folder in https://github.com/MoveOnOrg/Spoke/tree/main/src/integrations/texter-sideboxes will allow you to add a component to the sidebox
- Then for testing, make sure to add the new component name to the `TEXTER_SIDEBOXES` env var (example: `TEXTER_SIDEBOXES=contact-reference,tag-contact,new-module`

**Comment by JeremyParker** [comment]
Info about how it works is here:
https://developers.freshdesk.com/widget-api/
