### ISSUE TITLE
Bug: NGP VAN contact loading getting 400 error

### ISSUE THREAD

**Issue by bxjw** [ProgressiveCoders/Spoke#1568]
**Describe the bug**
I attempted to enable the NGP VAN contact loader, and am able to access saved lists, but get an error requesting the VAN export job with status 400. Granted, I might just be doing it wrong, given that documentation doesn't yet exist.

**To Reproduce**
I enabled an API key that allows export jobs and added that to the NGP_VAN_API_KEY and NGP_VAN_APP_NAME environmental variables. I also added "https://nameofapp.herokuapp.com" to NGP_VAN_WEBHOOK_BASE_URL.

**Expected behavior**
The contacts should be loaded via the export job.

**Platform (please complete the following information):**
 - OS: Mac Catalina
 - Browser Firefox
 - Desktop
 - Version 5.5

**Comment by ibrand** [comment]
@bxjw VAN is pretty new and undocumented, we'll have the documentation ready soon once the feature is no longer experimental. 

If I understand your workflow correctly, you're trying to export from the VAN UI into Spoke. You can't export lists from the VAN UI. Instead, you load contacts in from the Spoke UI.

If everything is enabled (including having your `CONTACT_LOADERS` env var set to include ngpvan) then you should see ngp van as an option in the dropdown menu for importing your contacts to start a campaign. That's where you would type in the list you want to load.

**Comment by bxjw** [comment]
Yes, apologies if I was unclear--that is what I did. The lists are
available in the dropdown menu but the export fails and gives a 400 error
on save.

**Comment by bxjw** [comment]
Looks like the Hustle key was what was needed after all, thanks @ibrand! This can be closed out.

**Comment by ozzy-simpson** [comment]
I'm now getting this error as well (I have all of the environment variables set correctly). It appears the issue is in the API key that's generated in [`src/integrations/contact-loaders/ngpvan/util.js`](https://github.com/MoveOnOrg/Spoke/blob/main/src/integrations/contact-loaders/ngpvan/util.js). The getAuth method defaults to using VoterFile mode (the `|0` at the end), which throws a 400 error if you're using VAN/EveryAction in MyCampaign mode (which has `|1` at the end). Maybe there should be an environment variable for this?
