### ISSUE TITLE
data exporting broken

### ISSUE THREAD

**Issue by mathemagica** [ProgressiveCoders/Spoke#161]
On the spoke campaign screen, click the export button, and see that it gets stuck at "exporting 67%". 
![screen shot 2017-08-28 at 1 23 24 pm](https://user-images.githubusercontent.com/2147383/29785136-85b7ec12-8bf4-11e7-943e-053fe035b513.png)

Scott tested is 8/9 and it worked then- related to latest lambda deploy?

**Comment by sreynen** [comment]
In my testing, exports never got above 0%. In inspecting graphql queries, I see the export job stays in "pendingJobs" forever, never gets processed. I believe this is due to a bug in how jobs gets processed with our current lambda deploy, per: https://github.com/MoveOnOrg/Spoke/blob/master/docs/DEPLOYING_AWS_LAMBDA.md

Specifically, we are handling some jobs immediately as part of the initial request, and other jobs via a job-runner request. That job-running request sends a "dispatchProcesses" command, which calls everything in syncProcessMap when JOBS_SAME_PROCESS is set, which it is. Currently the only thing in syncProcessMap is handleIncomingMessages, so that's the only job that gets run async. This would be fine if everything else ran synchronously, but it doesn't. I'm not entirely sure why it doesn't, but one likely reason is the lambda process needs to restart every 5 minutes, so if the job doesn't complete when the restart it happening, I think it will just got dropped and never finish.

I suggest we resolve this by processing all jobs in syncProcessMap. So if a job ever doesn't get processed in the original request, it will always get picked up by the second request.

If no one objects to this plan, I'll go ahead and make a PR, but wanted to write it down first in case someone sees a flaw in the plan. Also, this change may only get us back to the original reported problem, where exports get stuck at 67%.

**Comment by sreynen** [comment]
Passing additional processes to the job-handler request didn't work because the job is marked as assigned. I was also wrong about the main lambda process restarting every 5 minutes. It's not a constant-running process, only runs when API gateway makes a request, so it should be able to fully process every request that comes in. Problem is, it's not. So next step is figuring out why it's not.

**Comment by sreynen** [comment]
In test environment, export was dying in various places when the process ran out of memory, so noting that increasing memory allotment (or decreasing memory need) may eventually be required in production. But the main fix for this was https://github.com/MoveOnOrg/Spoke/pull/188 and https://github.com/MoveOnOrg/Spoke/pull/204, fixing the nodemailing secure setting.
