### ISSUE TITLE
Feature Request: Canned response tag association

### ISSUE THREAD

**Issue by ibrand** [ProgressiveCoders/Spoke#1645]
**Problem**
It will finish out the [tagging story](#1473) to allow canned responses to be associated with a tag so that when a texter clicks a canned response it automatically applies the tag that the admin wanted applied.

**Solution**
Create a field in canned responses for a tag that allows auto-completing with the tags that an admin has added. Allow 1-many tags to be filled in. Automatically apply those tags when that canned response is selected.

**Comment by schuyler1d** [comment]
Some good examples for many-to-many canned response-tag relationships:
* Wrong Number + Strong Support. This came up a lot in recent M4BL texting (edited) 
* For GOTV: you might want responses for Moved + Already Voted, Moved + Needs Absentee Ballot, etc..
* Multiple tags per canned response was almost the default for event recruitment campaigns, since you often have different responses based on the reason that people are/are not attending an event ("Won't Attend + Strong Support + Interested in Future Events", "Won't Attend + Strong Support + No Future Events", etc...)

(from Matteo)

**Comment by arena** [comment]
Just found this issue, is it supposed to be open? 
I'm about to add a similar issue about showing tags alongside the canned response they are associated with

**Comment by Frydafly** [comment]
Closing since adding multiple tags to canned responses can already be done! Thanks @agreenspan24
