### ISSUE TITLE
Make "Next" button light up when ready or simply not be grey

### ISSUE THREAD

**Issue by lady3bean** [ProgressiveCoders/Spoke#175]
Since the "next" button when setting up a campaign is grey, it confused me and made me think I still needed to click something in order to move on. It should either light up conditionally if there are things that need to be done before a user can go to the next step, or, be a color other than grey.

**Comment by ibrand** [comment]
I believe this issue is referencing this button which is now called "save and go to next section" which is green so I'm closing this issue

<img width="1156" alt="Screen Shot 2020-01-22 at 3 10 16 PM" src="https://user-images.githubusercontent.com/3953117/72930190-607d4f80-3d29-11ea-9eff-0af691eddfd6.png">
