### ISSUE TITLE
Texter reply screen is not updating reply number

### ISSUE THREAD

**Issue by sreynen** [ProgressiveCoders/Spoke#178]
After sending replies, number doesn't go down.

Also see #207 for wholistic 'bug'

**Comment by shakalee14** [comment]
**How it doesnt work** 

-When I'm texting, the bubble for replies doesn't update after you handle your replies. Example, I as a texter send 2/4 messages, and get 2 replies back. The number in the replies bubble updates with the first replies I get. Then when I actually reply to the appropriate contacts, the number in the replies bubble does not update (doesn't recalculate after handling addressing replies) in the texter campaign dashboard. But in the actual texter to do list, it only shows me the texting conversations I need to reply to (so that part is not broken).

See **1 of 1 in the right corner** (meaning I only have 1 person to reply to)

<img width="1440" alt="screen shot 2017-09-08 at 9 42 35 am" src="https://user-images.githubusercontent.com/16676323/30214553-ea3e6d3a-947a-11e7-86fb-4eb911e4cea1.png">

But in the dashboard it says I have **2 replies** to send
<img width="1422" alt="screen shot 2017-09-08 at 9 48 31 am" src="https://user-images.githubusercontent.com/16676323/30214646-34cddd90-947b-11e7-9d7e-6ce0bedbdb06.png">

**Comment by sandramchung** [comment]
I think this was fixed by https://github.com/MoveOnOrg/Spoke/pull/200
