### ISSUE TITLE
Bug: Admin campaign search hint text goes out of container

### ISSUE THREAD

**Issue by crayolakat** [ProgressiveCoders/Spoke#1838]
**Describe the bug**
The hint text for admin campaign search is going out of the container in 13" laptop screen.

**To Reproduce**
1. Log in as an admin
2. Click 'Campaigns' in the left menu
3. Observe the hint text for searching campaigns at the top of the page

**Expected behavior**
Hint text should fit in search container.

**Screenshots**
<img width="1440" alt="Screen Shot 2020-09-12 at 8 41 17 PM" src="https://user-images.githubusercontent.com/9382984/93007727-1bb55b80-f53a-11ea-9e6e-b85d948c6792.png">

**Platform:**
 - Browsers: Chrome, Safari
 - Desktop
 - Screen size: 13"

**Comment by stefanhayden** [comment]
Doing some research on this. This is a `Floating label` on a Material design `TextField`. The docs are here: https://material-ui.com/components/text-fields/#floating-label

ATM the docs say:
```
Floating label
The floating label is absolutely positioned, it won't impact the layout of the page. 
You need to make sure that the input is larger than the label to display correctly.
```

So sadly the library we use punts on this issue and says to just always make the label shorter than the input. Perhaps we need a different way to show this information outside of the input box.

**Comment by arena** [comment]
I think it's pretty intuitive that you type into the field with the magnifying glass and then hit enter. 

So, we could simply remove the hint text entirely. Just to make things clear though we could start putting a heading at the top of cards like this and then have some instructions at the bottom of the cards that might be helpful to new or rusty users. 

In this case, we could add a heading that says:
"Search for a Messaging Campaign"
And some instructions below that include 
"...type a campaign name into the search field and hit enter to search." 
It would be nice if those instructions also explained what the selections before the field do (I have no idea what those do because I'm not an experienced admin).

**Comment by mau11** [comment]
We are reviewing outstanding issues. Closing as we are combining issues (#1885) related to tooltips for a larger update.
