### ISSUE TITLE
Diagnose how assigning texters currently works (or doesn't)

### ISSUE THREAD

**Issue by sreynen** [ProgressiveCoders/Spoke#184]
For https://github.com/MoveOnOrg/Spoke/issues/177

**Comment by shakalee14** [comment]
**How it doesnt work** 

-When I'm texting, the bubble for replies doesn't update after you handle your replies. Example, I as a texter send 2/4 messages, and get 2 replies back. The number in the replies bubble updates with the first replies I get. Then when I actually reply to the appropriate contacts, the number in the replies bubble does not update (doesn't recalculate after handling addressing replies) in the texter campaign dashboard. But in the actual texter to do list, it only shows me the texting conversations I need to reply to (so that part is not broken).

See **1 of 1 in the right corner** (meaning I only have 1 person to reply to)

<img width="1440" alt="screen shot 2017-09-08 at 9 42 35 am" src="https://user-images.githubusercontent.com/16676323/30214553-ea3e6d3a-947a-11e7-86fb-4eb911e4cea1.png">

But in the dashboard it says I have **2 replies** to send
<img width="1422" alt="screen shot 2017-09-08 at 9 48 31 am" src="https://user-images.githubusercontent.com/16676323/30214646-34cddd90-947b-11e7-9d7e-6ce0bedbdb06.png">

**Comment by shakalee14** [comment]
I think this issue is two fold
- We currently attach auto assign to state and its automatically true when you visit this panel. So if you revisit this screen it'll try to auto-split contacts amongst texters
- Texting assignments are more stable after making sure information is saved. You can ensure it has saved after you press next and do a hard refresh. 

- Note - if you don't assign all the uploaded contacts to texters (say you upload 5 and only assign 3, then the panel for texters still stays yellow - which is misleading because you can still start the campaign)

**Comment by shakalee14** [comment]
You can test this theory by checking out this PR:
https://github.com/MoveOnOrg/Spoke/pull/195

**Comment by hiemanshu** [comment]
I'm currently looking at how texter assignments work. I'm doing this mainly to add a "Add All" button to the screen, so it adds all texters from that org onto the assignments screen. I'm getting this info from the `user_organization` table

**Comment by shakalee14** [comment]
Could you make an issue @hiemanshu for what you're working on so we can see whats coming down the pipeline? That feature sounds awesome! If you want to see what we're working on, we've created milestones for the project.

**Comment by hiemanshu** [comment]
Sure! I'll send out a PR today for the 'Add All' button, I finished with that. I'll add more things as they come up.

**Comment by sreynen** [comment]
Does the "Texting assignments are more stable..." point refer to saving the text assignments, or saving the contacts being assigned before adding the text assignments? And does more stable mean assignments saved exactly as they appear pre-save? Or is there still some uncertainty?

I think our overall goal in #177 is getting to the point where saving results in exactly what you'd expect, no surprises. I personally do a hard refresh after every section on the campaign edit form in testing, and find that to be entirely predictable, but I'm also testing with a very small number of contacts and testers, so I don't know if that entirely resolves the problem at scale.
