### ISSUE TITLE
It's possible to have zero steps in interactions and be unable to add a step

### ISSUE THREAD

**Issue by sreynen** [ProgressiveCoders/Spoke#185]
Steps to reproduce:

1) On campaigns list (/admin/{orgId}/campaigns), click + button.
2) Fill in Basics, Contacts, Texters sections, until all are green.
3) Under Interactions, add "hi {firstName}" in script input, nothing else.
4) Save Interactions section.
5) Open another section, then go back to Interactions.
6) If Interactions isn't yet empty, repeat steps 3-5.

When this happens, the Interactions section looks like this:

<img width="489" alt="screen shot 2017-09-06 at 11 15 14 am" src="https://user-images.githubusercontent.com/108645/30125143-b6312ac8-92f4-11e7-8593-786c5e03a082.png">

Then it's impossible to add steps to the interactions. The only option is to archive the campaign and start over.

**Comment by schuyler1d** [comment]
This occurs because if theres any way that the original interaction is deleted but nothing is saved in its place then the form goes screwy. A good way to solve this is on the backend if interaction steps ever returns nothing then it should send a fake new interaction step in its place to the client.  Ie the server ahould always send something

**Comment by zluo16** [comment]
@sreynen @schuyler1d I could take a look at this one!

**Comment by ibrand** [comment]
@schuyler1d is this still true?

**Comment by Frydafly** [comment]
@ibrand just tried these steps and the bug isn't coming up for me! 

confirming with @schuyler1d?

**Comment by schuyler1d** [comment]
no longer an issue
