### ISSUE TITLE
Feature Request: Darken the gray arrow for the response dropdown 

### ISSUE THREAD

**Issue by yogat3ch** [ProgressiveCoders/Spoke#1902]
**Problem**
A number of folks texting with us tonight did not realize that the question answer field was a drop-down due the faintness of the arrow on the right side of the field - pictured here in the lower circle:
![image](https://user-images.githubusercontent.com/32208821/101561388-44ab8800-3993-11eb-984a-2e91ec40a975.png)

**Solution**
Darkening it to the color below would help:
This CSS selector is from our instance
``` 
#undefined-Chooseanswer-CAMPAIGN-55248 > div:nth-child(1) > button {
fill: rgb(99 117 93);
}
```
This is what it would look like with that fill color:
![image](https://user-images.githubusercontent.com/32208821/101561626-a966e280-3993-11eb-99b2-6be60568bee8.png)

**Context**
Inside the Spoke Texter Todo - Reply interface

**Comment by arena** [comment]
This looks like an issue with the politics rewired fork of Spoke, here: https://github.com/politics-rewired/Spoke/issues
I agree that the way "current question" is implemented is confusing. It's been redesigned in this fork of Spoke so that the "answers" to the current question and the "canned replies" are consolidated into a single menu called "all responses" with a high-contrast drop-down arrow. I think that consolidation was one of the biggest wins in the redesign and made responding  with a scripted response a lot more intuitive. I hope that improvement will make its way into the Politics Rewired fork. 
cc'ing: @bchrobot and @ben-pr-p in case they want to bring it over to their issues.

**Comment by yogat3ch** [comment]
@arena Thanks for responding!
>It's been redesigned in this fork of Spoke so that the "answers" to the current question and the "canned replies" are consolidated into a single menu called "all responses" with a high-contrast drop-down arrow

This sounds a great deal more intuitive and easy to spot for some of the senior texters! thanks for updating me!

> I hope that improvement will make its way into the Politics Rewired fork.

I hope so too!
