### ISSUE TITLE
Opt-out reply cursor is buggy

### ISSUE THREAD

**Issue by schuyler1d** [ProgressiveCoders/Spoke#208]
Use case: want to say "Oh, no problem"   -- 
Experience: other letters start typing on the other side of of the cursor/built in reply.  cursor is a problem

Reproducing it:
1. click opt-out on a user
2. place your cursor with the mouse at the beginning of the text
3. start typing
Result: After typing a character the cursor moves to the end buggily

**Comment by sreynen** [comment]
Update: this seems to be an issue with material-ui and text inputs, documented here: https://github.com/callemall/material-ui/pull/7006

Updating material-ui to a version including that PR doesn't directly fix it, I think because the fix in that PR simple stops material-ui from causing a re-render, and Spoke code is causing a re-render in other ways.

In looking at other dialogs in Spoke and how they've avoided this problem, I've only found one other dialog that has a simple text input (vs. something that looks like a text input, but is actually more complex, with {token} strings, a select list, etc.): the "Invite new texters" dialog on the admin people page. That dialog has the same bug, but it doesn't matter in that context because the text input isn't being used for input, only copying a URL.

**Comment by sreynen** [comment]
After more testing with the latest stable version of material-ui (0.19.1), I haven't found a configuration that fixes this problem short of removing the dialog entirely, so I'm going to work on a non-dialog version of the opt-out interface.
