### ISSUE TITLE
Closing texter mode should go directly to /app/:organizationId rather than /app

### ISSUE THREAD

**Issue by schuyler1d** [ProgressiveCoders/Spoke#216]
I'm in an organization of my own ("scooby doo", orgid=4). When I go to 'switch to texter' (path=/app/4/todos) and then enter, then I click the 'X', it redirects me to path=/app which in turn redirects me to path=/app/3/todos (another org I'm a member of)

So this is a bug, but will affect few people.

**Comment by sandramchung** [comment]
Which user type or role are we talking about? 

For texters, their home screen after they login is the ToDo List:
<img width="365" alt="spoke" src="https://user-images.githubusercontent.com/5560919/30390713-3f5e53a0-9874-11e7-83ee-00e1c8544a07.png">
Clicking on any of the available tasks gets them to the texting interface:
<img width="388" alt="spoke" src="https://user-images.githubusercontent.com/5560919/30390750-5c8b2d4a-9874-11e7-8779-f51148bb8629.png">
And they can exit back to the ToDo List with the X in the upper right corner of the texting interface.

For organization Owners, their home screen is the organization's Campaigns admin:
<img width="428" alt="spoke" src="https://user-images.githubusercontent.com/5560919/30390863-b58ddb86-9874-11e7-852b-394e9d79d0c8.png">
And they get to their ToDo List by clicking "Switch to texter".
There's no way back from the ToDo List to the Campaigns admin except the back button. Is this what you are talking about?

I don't know what experience Admin users have, or what happens when an organization Owner owns multiple organizations. Superadmins don't see anything at all when they login until they are given a role in an organization.

**Comment by schuyler1d** [comment]
When I click the 'X' on your second screenshot, I get to a screen which says "Nothing to do" even though if I click back enough times or navigate from the beginning, I can get back to your first screenshot.  But maybe this is just an issue for Admins that have 'Switched to texter'.

If this is only for admins, then maybe it's not as high-priority as I thought.

**Comment by sandramchung** [comment]
I don't know how to reproduce what you've described - can you make a screen video or write out the process? Here is the dead end I've found: while logged in as an organization owner and having assigned contacts to myself in a campaign, after clicking Switch to Texter and completing all my ToDo list tasks, I can't even get back to the Campaigns admin with a back button.

**Comment by schuyler1d** [comment]
ok, i see what's happening to me on (on production). I'm in an organization of my own ("scooby doo", orgid=4).  When I go to 'switch to texter' (path=/app/4/todos) and then enter, then I click the 'X', it redirects me to path=/app which in turn redirects me to path=/app/3/todos (another org I'm a member of)

So this is a bug, but will affect few people.  I'll update the description and remove from milestone
