### ISSUE TITLE
Add ability to monitor texting activity stats in real time

### ISSUE THREAD

**Issue by sandramchung** [ProgressiveCoders/Spoke#296]
This is a feature request spawned from https://github.com/MoveOnOrg/Spoke/issues/276
For load and performance testing purposes, MoveOn and other heavy users need to be able to monitor various texting activity stats (e.g. outgoing messages, incoming messages, unique texters, unique contacts texted, all per unit time) in near real-time.

MO is already able to do this by querying our data warehouse copies of the application database, but in the future (and for more general use) we might consider implementing, for example, an activity admin in the UI or a Cloudwatch monitoring script.

**Comment by ibrand** [comment]
Closing because we do now have a polling mechanism on the texter stats in the campaign view: https://github.com/MoveOnOrg/Spoke/blob/main/src/containers/AdminCampaignStats.jsx#L356

That said, for huge campaigns there could be scaling issues here that involve rewriting the way that this data is queried. We could also always use more stats!
