### ISSUE TITLE
Make interaction step drop down a button on Texter view

### ISSUE THREAD

**Issue by shakalee14** [ProgressiveCoders/Spoke#342]
- Currently, in order to select an interaction step, you click on a drop down menu. This should be a button. 
- [ ] Create UX screen mock up for both desktop and mobile
- [ ] Implement mock up for desktop 
- [ ] Implement mock up for mobile

**Comment by shakalee14** [comment]
This menu for interaction step questions in the texter view happens here in this component:
https://github.com/MoveOnOrg/Spoke/blob/master/src/components/AssignmentTexterSurveys.jsx#L128

Which then is brought into this large container `AssignmentTexterContact.jsx` located here:
https://github.com/MoveOnOrg/Spoke/blob/master/src/containers/AssignmentTexterContact.jsx

A good place to start investigating how this section is rendered.

**Comment by ibrand** [comment]
@shakalee14 I'm cleaning up our `good first issues`s and want to know if this one was completed (since it's pretty old) or if it's open for new contributors to claim!

**Comment by shakalee14** [comment]
This is still open, thanks @ibrand

**Comment by arena** [comment]
I can't see the links (blobs) mentioned above ...

**Comment by ibrand** [comment]
@arena Found the lines. I think github changed their url structure since 2017 when Shaka made that comment:
https://github.com/MoveOnOrg/Spoke/blob/main/src/components/AssignmentTexterSurveys.jsx#L128

https://github.com/MoveOnOrg/Spoke/blob/main/src/containers/AssignmentTexterContact.jsx

**Comment by arena** [comment]
@shakalee14 What is an "interaction step" ?

**Comment by ibrand** [comment]
@arena an "interaction step" is what we refer to on the admin side as a script option. In the texter view I think Shaka is referring to the Question section here:

<img width="1440" alt="Screen Shot 2020-01-14 at 4 45 04 PM" src="https://user-images.githubusercontent.com/3953117/72385361-55a13a00-36ed-11ea-8688-a96e98ea86da.png">
<img width="1440" alt="Screen Shot 2020-01-14 at 4 45 09 PM" src="https://user-images.githubusercontent.com/3953117/72385365-5934c100-36ed-11ea-807a-e577439430bd.png">

Where you need to click that dropdown instead of just select a button like "Yes"

**Comment by arena** [comment]
Got it. Thanks for clarifying. I haven't explored the admin side but as I understand it there can be many of these steps and the "label" for them (that would appear on a button) can be any length. Do I have that right? Is there a character limit? Is there a limit to the number of answers per step?

**Comment by ibrand** [comment]
@arena There is no limit on number of answers or a character limit.

**Comment by ibrand** [comment]
Closing because the new texter UI includes this! #1493
