### ISSUE TITLE
Replace deprecated `apollo-server` library

### ISSUE THREAD

**Issue by jmcarp** [ProgressiveCoders/Spoke#391]
It's been replaced with https://www.npmjs.com/package/apollo-server-express.

**Comment by schuyler1d** [comment]
@jmcarp This is described here:
https://github.com/MoveOnOrg/Spoke/issues/224
Because it would take some time to figure out how to refactor/make all the changes for the new server, we have been procrastinating this.
If you'd like to take this on, let us know.  It would certainly be good to be up-to-date.
