### ISSUE TITLE
Add data-test-id attributes to DOM elements used in test interactions

### ISSUE THREAD

**Issue by sreynen** [ProgressiveCoders/Spoke#396]
Currently automated integration testing is limited by the difficulty of selecting specific elements. E.g. to tell a script to click the "+" button on the campaigns page to create a new campaign, the selector is currently `#mount div div div:nth-child(2) div:nth-child(2) div div:nth-child(3) button`, and that selector will stop working if the markup almost anywhere on the page changes. So this is a proposal to give the same element a more reliable selector like `button[data-test-id=new-campaign]`.

To avoid increasing the download size on prod, we could use something like https://github.com/coderas/babel-plugin-jsx-remove-data-test-id or https://www.npmjs.com/package/babel-plugin-react-remove-properties to remove these attributes from prod builds.

**Comment by shakalee14** [comment]
fyi @cp4r3z

**Comment by cp4r3z** [comment]
@shakalee14 @sreynen 

Sounds familiar! We've come up with a very similar solution which is currently being integrated in the following project:

https://github.com/MoveOnOrg/Spoke/projects/5

The new-and-improved selector for the above example will be: `[data-test=addCampaign]`

Instead of using another package to strip out the attributes, we add them conditionally based on `$NODE_ENV`.

**Comment by cp4r3z** [comment]
@shakalee14 @sreynen

Sounds familiar! We've come up with a very similar solution which is currently being integrated in the following project:

https://github.com/MoveOnOrg/Spoke/projects/5

The new-and-improved selector for the above example will be: `[data-test=addCampaign]`

Instead of using another package to strip out the attributes, we add them conditionally based on `$NODE_ENV`.
