### ISSUE TITLE
Make Send Button Bigger for First Texts on Mobile Devices

### ISSUE THREAD

**Issue by shakalee14** [ProgressiveCoders/Spoke#522]
Since we removed the other buttons for contacts who are getting the first texts, we have more room. Review screen shot:

<img width="457" alt="screen shot 2018-02-23 at 8 26 58 am" src="https://user-images.githubusercontent.com/16676323/36596385-8df972fe-1873-11e8-8167-17c00811ea6f.png">

**Comment by arena** [comment]
It's been a couple of years, but this still seems like a good suggestion

**Comment by arena** [comment]
@ibrand I think this might be a good first issue?

**Comment by ibrand** [comment]
Totally agree, thanks for resurfacing this @arena !

**Comment by arena** [comment]
I think this button could even be bigger than suggested. 
We can simplify the UI to make room for a huge button because:
- There is no need for the forward and back buttons in the "Send Initial Texts" flow
- The n of N counter is kinda confusing but could stay the same for now and move out of the way in the Send Initial Texts flow (imagine it on a line of it's own below the contact's name, etc at top)

Mockup showing a BIG send button:
![image](https://user-images.githubusercontent.com/411070/73095561-c4258b00-3e97-11ea-8761-6c31b7007a18.png)

**Comment by ibrand** [comment]
Closing because the new texter UI includes this! #1493
