### ISSUE TITLE
TEXTER: Texter able to send "blank" text message

### ISSUE THREAD

**Issue by Dayologic** [ProgressiveCoders/Spoke#587]
Description: The user is able to enter and send spaces in the "your message" field as a response to the user

ENV: STG
Browser: CHROME (latest)
OS: MacOS V10.12.5
Priority: LOW

Steps To Reproduce:

1) Login to Spoke Admin
2) Create A Campaign
3) Switch to texter view
4) Send message to texter
5) Verify/Receive a response
6) In "Your Message" field enter a few blank spaces and select send

Expected Result: The field validation recognizes that a valid response hasn't been sent

Actual Result: The system treats the spaces entered a valid character.

***Low Priority As The User Doesn't Actually Receive the Blank Message - but it impacts the admin texter flow as you'll have to wait for the user to respond before being able to send accurate messaging.***

SCREENSHOT:

<img width="1678" alt="blank_msg" src="https://user-images.githubusercontent.com/19258160/39932297-c4f10d68-550d-11e8-987f-a8a2a4ba6103.png">

**Comment by darvelo** [comment]
I'm working on this issue, now [writing a test](https://github.com/darvelo/Spoke/commit/103f539b146ecf7f3dc723ac2e7b6bb1a8053e79) (will squash commits after). I'm trying to simulate a button click using enzyme's `simulate()`, but it's not working. The codebase doesn't use `simulate()` anywhere… is it due to [the bug mentioned in this comment](https://github.com/MoveOnOrg/Spoke/blob/7f4f716d5fef38a8a154d8d13d8a9f9ddaf99de1/__test__/AssignmentSummary.test.js#L240-L243)?:

```
  // These are an attempt to confirm that the buttons will work.
  // It would be better to simulate clicking them, but I can't
  // get it to work right now because of 'react-tap-event-plugin'
  // some hints are here https://github.com/mui-org/material-ui/issues/4200#issuecomment-217738345
```

I'm going to install the Docker environment so I can run the full tests, and it looks like my change may break an [end-to-end test](https://github.com/MoveOnOrg/Spoke/blob/7f4f716d5fef38a8a154d8d13d8a9f9ddaf99de1/__test__/e2e/page-functions/texter.js#L13-L15). Is the test I'm writing better suited for e2e if `simulate()` isn't working?

**Comment by ibrand** [comment]
@darvelo did you end up finishing that PR ^? If not, do you have a WIP branch that someone could take to the finish line?

**Comment by darvelo** [comment]
@ibrand I do have a WIP branch up, though unfortunately I won't have any time to work on it. It can be found here: https://github.com/MoveOnOrg/Spoke/compare/main...darvelo:587-disallow-empty-texter-message

**Comment by ibrand** [comment]
Thank you! If anyone wants to take this change to the finish line, looks like that WIP branch is mostly done and just needs a few edits on the tests

**Comment by jasterix** [comment]
I'd like to work on this issue
