### ISSUE TITLE
TEXTER: Texter able to send consecutive messages to user

### ISSUE THREAD

**Issue by Dayologic** [ProgressiveCoders/Spoke#588]
Description: While engaging with a user via Spoke - the texter is able to send two consecutive messages without waiting for a user's response.  Current "Spoke" convention is to wait for user answer before sending responses

ENV: STG
Browser: CHROME (latest)
OS: MacOS V10.12.5
Priority: LOW

Steps To Reproduce:

1) Login to Spoke Admin
2) Create A Campaign
3) Switch to texter view
4) Send message to texter
5) While waiting for User to respond Select "Past Messages"
7) Enter a second message to the user

Expected Result: The system prevents the TEXTER from sending multiple messages to the user without first getting a response.

Actual Result: The TEXTER is able to send multiple messages to the USER without first getting a response.

Screenshot 1:

<img width="1672" alt="mark_spam" src="https://user-images.githubusercontent.com/19258160/39933604-743c7408-5511-11e8-9cb2-4287a2d4dbb9.png">

**Comment by arena** [comment]
I don't think this is a bug. There is a legit use case for this (especially on mobile where the text editing interface is so impossible to use) 

E.g.

texter: hi! will you do a thing?
contact: I would love to do that thing, but I moved, I'm in the hospital, and I also want to text ...can I do that?
texter: Sorry to hear that! I hope you are back to 100% very soon!
texter: Here's the info about how to text with us (canned response)
texter: Since you've moved, you need to sign up again here (canned response)

**Comment by ibrand** [comment]
I agree actually. I also think that allowing this is useful, and that written and social convention/guidelines can be used  for orgs that don't want texters to double text. I'm gonna close this one.

Thanks for the use case @arena !
