### ISSUE TITLE
NationBuilder Integration

### ISSUE THREAD

**Issue by shakalee14** [ProgressiveCoders/Spoke#592]

**Comment by mbpoland** [comment]
Would help significantly with uptake of Spoke in Australia, leading up to the 2018/19 elections. The majority of grassroots progressive groups use NB still and most don't have an in-house developer or data capacity. Similar NB integration to CallHub would be ideal.

**Comment by Frydafly** [comment]
@anthonymockler fyi! I'll close this issue once you write yours up, since this one needed rewriting & planning

**Comment by bxjx** [comment]
@Frydafly @AnthonyMockler oh this reminds that we did implement a NationBuilder event RSVP action handler at GetUp. I'll see if I can grab the code and create a PR.

**Comment by Frydafly** [comment]
Woo! @bxjx

**Comment by AnthonyMockler** [comment]
Thanks Bridger! That would be amazing. Did you also build a contact loader
for NB?

**Comment by bxjx** [comment]
@AnthonyMockler alas no. We used a different tool for that.

**Comment by Arique1104** [comment]
Hello,

My name is Arique (they/them) and I am the Community Manager for Spoke. First of all, thank you so much for creating this issue and for everyone’s contributions to this ticket.

I am going through all of our issues and beginning to close all issues created in 2018 or older. Your issue qualifies.

I am giving everyone one week to answer the following question: 

- **Has this issue been resolved during the subsequent Spoke Updates?**

On November 16th I will be closing this issue if:
1. There is no response
2. You respond yes

If you are reading this message after November 16th, please note that if you tag me and answer the above question, I will be happy to reinstate the issue.

**Comment by Arique1104** [comment]
This issue is considered resolved.

**Comment by poketama** [comment]
@Arique1104 as discussed above

It would be quite useful to have Spoke able to open up the NationBuilder profile of a person, and to directly import lists from Spoke. In my organisation in Australia our current workflow is to export NB lists as CSV and put them on Spoke, which isn't too much work. Then when texting we use a custom "Who is this person" canned response to bring up their name and number, which we can use to search NationBuilder. Naturally, that second part takes a lot of time and it would be great to have some sort of integration or quickloading of the profile. 

Actually, maybe even just having an option to show the persons phone number under their name? You could maybe click to copy it as well. This would save a fair bit of time instead of doing the canned responses step.
