### ISSUE TITLE
Improve sendMessage speed

### ISSUE THREAD

**Issue by shakalee14** [ProgressiveCoders/Spoke#6]
- [x] Assign contact number upon signup instead of on first text
- [x] Move more of the method of sendMessage into the async part of sendMessage. See if we can get it down to < 50ms.
- [x] Make it threadsafe so we can have multiple message senders. Possibly look into using my new job queue to do this, creating a queue per number.

**Comment by shakalee14** [comment]
Believe this also could be a server issue

**Comment by sreynen** [comment]
From chat, my understanding is the key thing we're trying to speed up here is the interface of sending messages, not the actual delivery speed. I attempted to time how long the interface takes to move from sending to the next contact and found it at least feels instance. I'm not 100% it's <50ms, but only because 50ms turns out to be faster than I can hit "stop" on a timer.

We already have multiple message sender workers, each running as a separate process, which I believe is as threadsafe as nodeJS can be.

So I think this issue may be resolved, and if it's not, I would like more context on what we want to speed up.
