### ISSUE TITLE
Datawarehouse contact upload can max-out on short-lived backends (like AWS Lambda)

### ISSUE THREAD

**Issue by schuyler1d** [ProgressiveCoders/Spoke#672]
In https://github.com/MoveOnOrg/Spoke/blob/main/src/workers/jobs.js#L148
The full query is done at once, and contacts are updated in a single go.

For very large queries, this will timeout (or run out of memory or both) in constrained environments like AWS Lambda.

On conditions:
* `SELECT COUNT(*) FROM (<QUERY>)` and yields more than 10-20k contacts
* Somehow we detect having a 'dispatcher' available, (see https://github.com/MoveOnOrg/Spoke/blob/main/lambda.js#L43-L58)

1. Queries should be batched into groups of 10-20k with LIMIT OFFSET appends -- at least when a pre-query runs with 
2. Dispatch to a lambda sub-task one of the OFFSET/LIMIT batches (the SQL query itself will also need to be sent, of course)
3. As it continues, the Job status should be updated.

If that works in parallel, then great -- otherwise, we may need to do it 'serially' -- where a lambda job is sent the first, iterates through the offsets until it's run out of time and then dispatches another one to continue the work.  We should do what's most reliable and will also work predictably and dependably.

**Comment by shakalee14** [comment]
Related to https://github.com/MoveOnOrg/Spoke/issues/356

**Comment by mathemagica** [comment]
For very large contact files, instead of querying for the data directly, I wonder if we should instead do a dump and load of data, from our redshift data warehouse into RDS postgres: 
 - we could async dump the result of the contact query from redshift into s3, and then async import the data file from s3 into postgres: https://stackoverflow.com/questions/36502409/export-from-amazon-redshift-into-an-rds-mysql-database
 - it's also possible for RDS postgres to open a direct data link to redshift: https://www.postgresql.org/docs/9.1/static/dblink.html

Probably worth testing these options manually to understand how long they take for files of various sizes.

**Comment by schuyler1d** [comment]
cool options!  That's not my current approach, but especially the first seems like it could be useful.  The one downside is right now we do post-processing on the rows, so only a specific set of queries or some work to write the query properly would be required to load directly into postgres -- i.e. we'd need it in the right format already, rather than process it.
