### ISSUE TITLE
Mobile Responsive View for Texter

### ISSUE THREAD

**Issue by shakalee14** [ProgressiveCoders/Spoke#9]
- [ ]  As a user, I should be able to easily use app on my phone. 
- [ ] Convert links to actual links
- [ ] Texter campaign dashboard responsive to mobile (profile and landscape)
   - [ ] `Too early to send messages` button text bleeds
   - [ ] contacts count for send first, replies, and too early categories is too small on mobile
- [ ] Texting dashboard buttons are scrambled in sizes and inconsistent
   - [x] Send button needs to be more prominent
   - [ ] Cannot scroll in conversation to previous texts
   - [x] Exit button isn't prominent

**Comment by shakalee14** [comment]
- As a user, I should be able to easily use app on my phone.

**Comment by shakalee14** [comment]
- [ ] Admin dashboard responsive to mobile 
- [ ] Texter dashboard responsive to mobile without turning the device horizontal

**Comment by shakalee14** [comment]
Currently, mobile texter view is unusable because of styling.

**Comment by shakalee14** [comment]
Accessibility issues around links not being actual links.

**Comment by sandramchung** [comment]
Can you clarify what changes on what device screen are needed for these items:

Texting dashboard buttons are scrambled in sizes and inconsistent
-  Send button needs to be more prominent
-  Cannot scroll in conversation to previous texts
-  Exit button isn't prominent

The current screenshot in Chrome mobile device emulator doesn't appear to have these issues. The iPhone 6 version might have some overlapping buttons, and I think the Opt Out button should say "Opt Out" instead of just looking like a cancel symbol - the hover text that says "opt out this contact" doesn't show up on mobile. Here's what iPhone 5 looks like:

<img width="337" alt="spoke" src="https://user-images.githubusercontent.com/5560919/29286325-e37fd370-80ee-11e7-9997-167de30f287b.png">

**Comment by shakalee14** [comment]
Most styling issues on texter view come into play after the conversation has already started. So I see this behavior on mobile which also disallows me to scroll up above current question survey prompt. Does that make sense? I think the exit button is actually fine and opt out button `saying opt out` instead of the icon is a good move. And for the send button, maybe making it a full length button is better for accessibility? 

For this process, I'm not sure what's the best move for us since we don't have mocks or are designers, but we recognize that some changes need to be made for the mobile texter view. 
![image_uploaded_from_ios_720](https://user-images.githubusercontent.com/16676323/29286546-6ad134ca-8100-11e7-9c6c-b7724619af9f.jpg)

**Comment by sandramchung** [comment]
Let's get the exact mobile screen issues documented from the texter user's perspective with screen caps and device type. I can do straightforward fixes like "make the numbers in the bubbles bigger and the text shorter on this button", but I'm not going to solve UI problems with vague feedback like "Send button needs to be more prominent", especially when I can't reproduce those problems. The Send button is quite prominent in my device emulator for iPhone 5 and so is the pager that lets you swap conversations.

I'm looking for a description of the user task that the texter failed to complete, with a screen capture of what they're seeing. E.g. "On reply screen after receiving a response from contact, mobile testers using iPhone 4 could not figure out how to exit conversation" with a screen cap from that tester's device. Different device screens might present different problems, so it's important to test with real mobile devices and more than one kind.
