### ISSUE TITLE
Hard to find campaigns 

### ISSUE THREAD

**Issue by suegibson** [ProgressiveCoders/Spoke#906]
There must be some sort of rhyme/reason to the way campaigns are ordered in Spoke. As a user, can I be privvy to it, please? In the archive, it looks at first as if it’s meant to be numerically by campaign number, but that theory soon goes off the rails. In active campaigns, I don’t have a clue. Working up to the general election will be hellacious if I can’t get this answered. @lperson @codygordon @joemcl

**Comment by lperson** [comment]
@suegibson campaigns are ordered in descending order by campaign due date (latest due dates first, nearest due dates last), and if there are ties, campaigns with the same due date are in the order in which the campaigns are added.

What is the most useful way arrange the campaigns?

Would it help if we added a little widget that lets you filter campaigns, for example, start typing the name of the campaign or the id number?

**Comment by ZevH** [comment]
There are situations in which it is useful to order campaigns in different ways. It would be ideal if there could be a drop-down menu for selecting different orders. For example, I would like to see:
1) due date (ascending or descending);
2) creation date = campaign number (ascending or descending);
3) text-assignment (all "orange" campaigns at top, all "green" campaigns below; with secondary sort by due date)
4) alphabetical by campaign name
Perhaps there are others that would be useful.

**Comment by suegibson** [comment]
Oh my gosh: Yes, Larry! That would be a huge relief! I also support Zev’s idea. Whatever’s easier😊
Thank you for the reassignment solution as well!
Sue
#WhiteSilenceIsViolence

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by suegibson** [comment]
I need to be able to filter by time zone, @lperson

**Comment by suegibson** [comment]
I can now find campaigns using @joemcl’s suggestion to use the Find on Page feature; @ZevH, you may find that useful until we get the Sort By drop down menu.

**Comment by suegibson** [comment]
Yes, thank you, @harpojaeger. Toward the end of the day, I need to prioritize having texters manage replies in the Eastern Time Zone first, and it would be helpful to be able to find them expeditiously. Same with getting started in the mornings.

**Comment by harpojaeger** [comment]
When you say "find them," what are you referring to? IIUC, this issue is about sorting campaigns, not texting assignments within a campaign. Are you saying you want a filter option that shows you campaigns with contacts assigned in a particular timezone that have not been replied yet? Or is there some other metadata about the campaign that you want to be able to filter on? Trying to understand the specific desired behavior here.

**Comment by suegibson** [comment]
It would be great to see all campaigns in a particular time zone at a glance in Campaigns view, and it would be great if their conversations Needing Texter Response were searchable by time zone as well.

**Comment by harpojaeger** [comment]
What do you mean by "campaigns in a particular time zone"? I don't remember campaigns having a "timezone" attribute. They have active hours, which are specified with a timezone; is that what you mean? Or did #838 change this in a way I'm not aware of?

**Comment by suegibson** [comment]
Since we now enforce texting hours within each campaign, it seems to me that Spoke should be able to identify them for us. Would we do better on the phone?

**Comment by joemcl** [comment]
@harpojaeger we run campaigns across the country. In setting up a campaign with an instance running @lperson 's excellent Message Review, one can set "texting hours" for a campaign by time zone. @suegibson is referring to time zones as set by texting hours, and of course the geographic location/time zone of the campaign, and the time zone for volunteer text senders. So in the screenshot below the time zone for texting hours is set to the Pacific time zone. As well, even without that setting, a .csv loaded with zips in a particular time zone affects texting hours. 

![14ffbcc0-058e-4315-99a6-b924cc3ca233](https://user-images.githubusercontent.com/3912434/52009115-f835be00-2486-11e9-8e04-4d2bffc3fbbc.jpg)

**Comment by harpojaeger** [comment]
Okay, understood. So @suegibson, what you're saying is you'd like a filter that shows only campaigns whose texting hours, whatever they might be, are defined in a given timezone. Do I have that right?

The reason I'm asking these questions (and I know it seems a little silly to have to be so specific) is because I want to avoid the situation where a dev (say, me, or a new person looking for an issue) writes what they _think_ you want and then finds out it doesn't actually solve the problem you were trying to solve. It's worth making extra-sure we're all on the same page and that we're all using the same language to refer to the same things, rather than writing the wrong code up front and then having to go back and change it.

**Comment by harpojaeger** [comment]
@joemcl I have two more questions for you, based on your comment above. You're talking about three possible definitions of "time zone":

1. "time zones as set by texting hours,"
2. "the geographic location/time zone of the campaign," and
3. "the time zone for volunteer text senders."

It sounds like @suegibson is talking about 1. I don't understand what numbers 2 and 3 mean, which is why I'm trying to clarify here. Is 2 the same as 1? And given that volunteer texters for any given campaign could be in any timezone anywhere, what does 3 signify?

**Comment by joemcl** [comment]
@harpojaeger sorry, to clarify - yes @suegibson is just talking about 1. I refer to 2 and 3 because @suegibson and I and others are often trying to juggle/compare 1 to 2 and 3 - so for example, a campaign running in the Pacific time zone and looking to plug in texters in that same time zone, or folks in a different TZ - like in Eastern TZ but able and willing to text after 9PM Eastern to voters in a Pacific time zone campaign. So it occurs to me that being able to also see and sort and filter users in People by time zone would also be handy for matching to campaigns and find available text senders - we basically do that in Slack, based on a time zone in a Slack user profile,  or based on what we have (if anything) in the user/sender table for time zone location in Airtable, or just from memory of who is in what TZ among the most active text senders.

**Comment by suegibson** [comment]
I am not interested in #3, and #s 1 and 2 look like essentially the same thing to me.

**Comment by harpojaeger** [comment]
@joemcl What do you mean by "1 and 2 are always set to the same time zone?" Does WFP have some internal way you track which timezone a campaign is in? Do you create separate campaigns for contacts in each timezone? What I'm trying to zero in on here is which actual data that Spoke stores about the campaign you're referring to. @suegibson is talking about the timezone the campaigns' active hours are set to, but it sounds like you're saying 2 is different than that, and I want to understand that.

**Comment by joemcl** [comment]
@harpojaeger what I mean is that a campaign may be for a campaign for example in the Central time zone - like for a candidate in Chicago - and that the texting hours for that campaign should be set to that time zone on creation. But, sometimes, that does not happen :) - the person creating the campaign forgets to do that .  For example, if we know from the campaign description, etc that it's for a candidate in Chicago, the time zone in texter hours should be set to Central on set up, not left at default Eastern time zone, so texters aren't kicked off from being able to send at 8PM Central time / 9PM Eastern time rather than 9PM Central time.

**Comment by ibrand** [comment]
Closing because the functionality here is the same as #1007
