### ISSUE TITLE
feature request -- texter dashboard enhancements

### ISSUE THREAD

**Issue by trickfilm** [ProgressiveCoders/Spoke#957]
It would be interesting (and motivating!) if I as a texter could see my personal stats in my dashboard. How many total texts I've sent (in all campaigns), percentages of 'yes' and 'no' responses, and how these compare to the global total. Maybe some kind of badge or prize when certain quantities are reached? The MoveOn phone-bank tool had something like this IIRC.

I assume all this info exists in the db somewhere and could be displayed to the texter without too much difficulty?

**Comment by DinahSanders** [comment]
Our leadership team had a serious discussion about this when we were considering posting a "leaderboard" each week (based on the stats Erik could see as an administrator), and we decided firmly against it because it would be discouraging to our texters who don't have a chance of being celebrated in this way. 

The ability to send more texts depends on things like
- having a fast internet connection;
- having more time which you are able to dedicate to texting;
- being physically able to send texts faster and/or for longer periods of time; 
- having multiple devices so you can text from more places (e.g., from your phone while in line at the store, from your tablet while watching TV at night with family);
- being more technically savvy and able to quickly move between Spoke, Slack, and reference materials in the browser.

All of these things correlate with privilege.

So, for the same reason you wouldn't want to send out fundraising emails with "make the leaderboard of biggest donors to our campaign in your area"—that it would be demoralizing to small, but committed donors and would actively work against growing diverse representation in your organization—it's probably a bad idea to make texting totals something announced to the team. In grassroots activism not only does all participation matter, it's the number of reliable, engaged volunteers that makes the difference when actions are happening in the district. 

If there are going to be public stats, they should emphasize the desired behaviors that do not require privilege to achieve and aren't dependent on the kind of campaigns you happen to get assigned to (e.g. Call Congress, with the phone number in the initial text is going to have way fewer 'Yes' responses while being just as successful in resulting actions by our contacts as we measure them outside of Spoke):
- a run streak of participation week-on-week, maybe building your "Resistance Ribbon" as long as you can make it;
- consistently sending all texts in every assigned workflow in a week, month, quarter, or year (but then the problem can be 'what if a technical problem causes someone to have to stop doing a workflow?' However it's designed has to not have glitches mess up the personal stats.)


This doesn't mean that an enhancement to allow a texter to privately see their sent texts count would be a bad thing, but that it should be designed in the context of a cooperative not competitive environment.

**Comment by trickfilm** [comment]
interesting, and thanks for the detailed response. I am probably the least competitive person you’ll ever meet, so this isn’t about trying to outperform other people. 

I guess I’m less interested in how I compare to other texters in terms of raw numbers, more interested in the _percentage_ of my texts that get a ‘yes’ response. Since it can be demoralizing to send 2000 texts and get (say) 20 responses of any kind, of which maybe 5 are ‘yes’, I’d like to know that my experience falls within the normal range. (unlike the comparable scenario with the ‘donor leaderboard’, which I too find coercive and gross, a higher or lower success rate _if expressed as a percentage_ doesn’t reflect on the skill or commitment level of the texter. If anything, it measures whether or not the admin wrote an effective message).

Analytics of this kind might even allow the admins to try different versions of the message to see if one works better than another.

Anyway, thanks for the good work! This sure beats phone banking.

Luke Jaeger | www.trickfilm.org

**Comment by DinahSanders** [comment]
Remember that, unless your organization sends only to contacts who have pre-approved blast messages, all outgoing texts must be monitored to remain in compliance with federal rules against automated sending to those who have not been opted in.

Be sure you are following the volunteer agreement terms and instructions for your organization.

**Comment by arena** [comment]
I don't want a leaderboard, I just want to see how many texts I've sent all time, this week, today

**Comment by ibrand** [comment]
@arena do you think we should make a new issue for that kind of dashboard enhancement? It seems a little different than the initial intent of this issue.

I'd be inclined to make a new issue and close this one

**Comment by arena** [comment]
https://github.com/MoveOnOrg/Spoke/issues/1361

**Comment by ibrand** [comment]
Closing due to @DinahSanders giving a really thoughtful case against it.
